### ISSUE TITLE
TestNG plugin 7.8.0 requires that I add slf4j to classpath

### ISSUE THREAD

**Issue by JFK-DXML** [testng-team/testng-eclipse#559] opened 2023-09-14 17:15 UTC
### Problem Statement
Upgrading to TestNG Eclipse plugin 7.8.0 seems to require slf4j to the Eclipse build path whereas previously it did not

<img width="915" alt="Screenshot 2023-06-13 at 10 47 07" src="https://github.com/testng-team/testng-eclipse/assets/105439734/cce4b7a0-485e-40d5-918b-377b9e016188">

- install Eclipse IDE for Java Developers 2023-06 (4.28.0)
- Install TestNG plugin (version 7.8.0) from marketplace into Eclipse as per normal.
- Make sure Eclipse project is configured with TestNG library from plugin
- Run some TestNG tests as normal. slf4j is NOT on the build classpath in Eclipse or ant
- Exception is thrown
  - Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory.
    - at org.testng.log4testng.logger.Logger.lamda$getLogger$0(Logger.java:30)

- Add slf4j-api-1.7.25.jar to the build path for the Eclipse project
 - TestNG test runs successfully

- Remove slf4j-api-1.7.25.jar from the build path for the Eclipse project
- Uninstall TestNG plugin
- Install TestNG plugin (version 7.4.0) from update site  https://testng.org/testng-eclipse-update-site/7.4.0
- TestNG test runs successfully

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
Nothing pertinent

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [x] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

We have a strange build setup which uses the java Builder synchronized with an an build.xml to build things

### Operating System

- [ ] Windows
- [ ] Linux
- [x] OSX MacOS 12.6.7 Apple M1 Max (aarch 64)

**Comment by missedone** [comment] 2023-09-22 18:43
@JFK-DXML , thanks for reporting the issue, i can reproduce it on eclipse 2023-09 as well, let me see how to fix it

**Comment by missedone** [comment] 2023-09-22 18:52
oh, wait, i got a different error not relate to this.

**Comment by missedone** [comment] 2023-09-22 18:53
@JFK-DXML , the slf4j jar is in the testng-p2 update site https://github.com/testng-team/testng-p2-update-site/tree/main/updatesites/7.8.0.r202306071539/plugins

pls double check if it's on your installed plugin list 
<img width="761" alt="image" src="https://github.com/testng-team/testng-eclipse/assets/555134/8ec19c2e-9bcb-4fb5-a08c-bd4bda467412">

**Comment by missedone** [comment] 2023-10-01 17:40
@JFK-DXML do you see any error on the "Error Log" view
<img width="451" alt="271844355-8d345cfe-8398-4fe5-ab72-47de7ed52022" src="https://github.com/testng-team/testng-eclipse/assets/555134/bcb05f24-a6a7-4f4d-af3d-02e6ac65fb2e">

**Comment by SantiBailors** [comment] 2023-10-02 10:09
I have the same, I had initially reported it at #533 ([post](https://github.com/testng-team/testng-eclipse/issues/533#issuecomment-1741735899)) and I was rightfully pointed here so I'm continuing my report here.

I get no errors in the Error Log after I run the problematic test:

![image](https://github.com/testng-team/testng-eclipse/assets/7628280/d5dff9a5-4a36-4d58-a6b7-58ede3613f66)

However I do get a TestNG-related error there when I do "Check for updates":

![image](https://github.com/testng-team/testng-eclipse/assets/7628280/02f02bb9-bf31-42ae-a94b-9146f71e91f7)

![image](https://github.com/testng-team/testng-eclipse/assets/7628280/ad9fcbac-df07-451a-8aab-536018e1e464)

Re the plugin list mentioned above by @missedone, I do not have that plugin. This is the list filtered by typing "slf":

![image](https://github.com/testng-team/testng-eclipse/assets/7628280/722bf977-5d47-4a83-8f36-983d3a5c4a63)

This is what I have under "Available Software Sites" (list filtered by typing "testng"):

![image](https://github.com/testng-team/testng-eclipse/assets/7628280/3a34d339-ff8c-4acf-bfa7-f9f8bdb2b269)

I did not try to manually add the update site mentioned above by @missedone because I don't want a workaround of adding an update site address specific to a given version (I prefer to keep my workaround of manually adding the slf4j-api jar (https://www.slf4j.org/download.html) to the build path as it's more likely that I will remember to remove it when this error is fixed), but if that helps I can do that and report the outcome.

**Comment by JFK-DXML** [comment] 2023-10-02 14:51
> @JFK-DXML , the slf4j jar is in the testng-p2 update site https://github.com/testng-team/testng-p2-update-site/tree/main/updatesites/7.8.0.r202306071539/plugins
> 
> pls double check if it's on your installed plugin list <img alt="image" width="761" src="https://user-images.githubusercontent.com/555134/270031795-8ec19c2e-9bcb-4fb5-a08c-bd4bda467412.png">

<img width="809" alt="Screenshot 2023-10-02 at 15 44 23" src="https://github.com/testng-team/testng-eclipse/assets/105439734/5d5ba015-fb99-4616-a669-0ddfb4e6e901">

**Comment by JFK-DXML** [comment] 2023-10-02 14:58
> @JFK-DXML do you see any error on the "Error Log" view
> 

<img width="1407" alt="Screenshot 2023-10-02 at 15 57 00" src="https://github.com/testng-team/testng-eclipse/assets/105439734/0569d6e6-9281-433b-b267-d198bdfd97f0">
<img width="1015" alt="Screenshot 2023-10-02 at 15 55 55" src="https://github.com/testng-team/testng-eclipse/assets/105439734/d2fb3148-714a-43d0-a35a-8ed801a55564">

**Comment by missedone** [comment] 2023-10-02 15:01
> > @JFK-DXML do you see any error on the "Error Log" view
> 
> Here is what I see when running the test
> 
> <img alt="Screenshot 2023-10-02 at 15 57 00" width="1407" src="https://user-images.githubusercontent.com/105439734/272006807-0569d6e6-9281-433b-b267-d198bdfd97f0.png"> <img alt="Screenshot 2023-10-02 at 15 55 55" width="1015" src="https://user-images.githubusercontent.com/105439734/272006831-d2fb3148-714a-43d0-a35a-8ed801a55564.png">

Could you share the detail of the message field in the screenshot, most important is the classpath list in the message

**Comment by missedone** [comment] 2024-01-15 15:56
closing this as 7.9.0 should have solved this issue.

see https://github.com/testng-team/testng-eclipse/issues/561#issuecomment-1883393683

**Closed by missedone** 2024-01-15 15:56 UTC
